=== soumitri2001/Labs-JU-UG3/WebTech-Lab-UG3/A1/Q9/Q9.dtd
<!ELEMENT question-paper (question*)> 
<!ELEMENT question (text, optionA, optionB, optionC, optionD, answer)> 
<!ELEMENT text (#PCDATA)> 
<!ELEMENT optionA (#PCDATA)> 
<!ELEMENT optionB (#PCDATA)> 
<!ELEMENT optionC (#PCDATA)> 
<!ELEMENT optionD (#PCDATA)> 
<!ELEMENT answer (#PCDATA)> 
 <!ATTLIST question no CDATA #REQUIRED> 
<!ATTLIST answer value  (optionA|optionB|optionC|optionD) #REQUIRED>

=== soumitri2001/Labs-JU-UG3/WebTech-Lab-UG3/A1/Q9/Q9.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE question-paper SYSTEM "./Q9.dtd">
<question-paper>
    <question no="1">
        <text>What is the capital of India ?</text>
        <optionA>Kolkata</optionA>
        <optionB>New Delhi</optionB>
        <optionC>Mumbai</optionC>
        <optionD>Prayagraj</optionD>
        <answer value='optionB'>New Delhi</answer>
</question>
</question-paper>
